<a href="https://colab.research.google.com/github/tarannump096-cpu/My-Projects/blob/main/Probability14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("diet_recommendation_dataset_1000.csv")

In [ ]:
df

,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Sugar_Level,Cholesterol,Goal,Diet
0,56,0,145,118,56.1,0,131,169,2,Low Carb
1,46,1,166,62,22.5,0,118,253,2,Diabetic
2,32,0,170,83,28.7,1,78,256,2,Diabetic
3,60,1,162,116,44.2,2,161,199,0,Diabetic
4,25,0,158,61,24.4,1,100,237,1,Heart Healthy
...,...,...,...,...,...,...,...,...,...,...
995,23,1,173,52,17.4,2,172,261,2,Diabetic
996,43,1,165,52,19.1,2,175,156,2,Diabetic
997,21,0,159,70,27.7,1,126,177,0,Low Carb
998,36,1,171,41,14.0,2,149,249,0,Diabetic
999,37,1,175,55,18.0,1,168,161,1,Diabetic

In [ ]:
x=df.drop(columns=["Diet"])

In [ ]:
y=df["Diet"]

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=365,stratify=y)

In [ ]:
ss=StandardScaler()

In [ ]:
le=LabelEncoder()

In [ ]:
xtrain_scaled=ss.fit_transform(xtrain)

In [ ]:
xtest_scaled=ss.transform(xtest)

In [ ]:
ytrain_scaled=le.fit_transform(ytrain)

In [ ]:
ytest_scaled=le.transform(ytest)

In [ ]:
xtrain_scaled.shape

(800, 9)

In [ ]:
xtest_scaled.shape

(200, 9)

In [ ]:
ytrain_scaled.shape

(800,)

In [ ]:
from sklearn.feature_selection import SequentialFeatureSelector

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
model=LogisticRegression(max_iter=1000)

In [ ]:
ffs=SequentialFeatureSelector(
    model,
    n_features_to_select=5,
    direction='forward',
    scoring="accuracy",
    cv=5
)

In [ ]:
ffs.fit(xtrain_scaled,ytrain_scaled)

SequentialFeatureSelector(estimator=LogisticRegression(max_iter=1000),
                          n_features_to_select=5, scoring='accuracy')

In [ ]:
ffs.get_support()

array([False, False, False,  True,  True,  True,  True,  True, False])

In [ ]:
x.columns

Index(['Age', 'Gender', 'Height_cm', 'Weight_kg', 'BMI', 'Activity_Level',
       'Sugar_Level', 'Cholesterol', 'Goal'],
      dtype='object')

In [ ]:
ffs_features=x.columns[ffs.get_support()]

In [ ]:
ffs_features

Index(['Weight_kg', 'BMI', 'Activity_Level', 'Sugar_Level', 'Cholesterol'], dtype='object')

In [ ]:
bfs=SequentialFeatureSelector(
    model,
    n_features_to_select=5,
    direction='backward',
    scoring="accuracy",
    cv=5
)

In [ ]:
bfs.fit(xtrain_scaled,ytrain_scaled)

SequentialFeatureSelector(direction='backward',
                          estimator=LogisticRegression(max_iter=1000),
                          n_features_to_select=5, scoring='accuracy')

In [ ]:
bfs_features=x.columns[bfs.get_support()]

In [ ]:
bfs_features

Index(['Weight_kg', 'BMI', 'Activity_Level', 'Sugar_Level', 'Cholesterol'], dtype='object')

In [ ]:
ffs_features

Index(['Weight_kg', 'BMI', 'Activity_Level', 'Sugar_Level', 'Cholesterol'], dtype='object')

In [ ]:
x.corr(method="pearson")

,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Sugar_Level,Cholesterol,Goal
Age,1.000000,-0.028480,-0.045504,0.031570,0.044260,-0.019433,-0.033849,-0.023504,-0.003518
Gender,-0.028480,1.000000,-0.035237,0.037671,0.048753,-0.047744,-0.000108,0.016309,0.049793
Height_cm,-0.045504,-0.035237,1.000000,-0.020084,-0.487809,0.035577,-0.011179,-0.017428,-0.030967
Weight_kg,0.031570,0.037671,-0.020084,1.000000,0.870239,-0.019191,-0.041038,0.000649,0.015662
BMI,0.044260,0.048753,-0.487809,0.870239,1.000000,-0.034631,-0.026204,0.004125,0.025448
Activity_Level,-0.019433,-0.047744,0.035577,-0.019191,-0.034631,1.000000,0.047111,0.015233,0.000686
Sugar_Level,-0.033849,-0.000108,-0.011179,-0.041038,-0.026204,0.047111,1.000000,0.027882,-0.040996
Cholesterol,-0.023504,0.016309,-0.017428,0.000649,0.004125,0.015233,0.027882,1.000000,0.013310
Goal,-0.003518,0.049793,-0.030967,0.015662,0.025448,0.000686,-0.040996,0.013310,1.000000

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn=KNeighborsClassifier(n_neighbors=5)

In [ ]:
#x_without_weight=
#x_with_weights=
#build a KNN model usin both
#check the CV score and compare
#less drop in accuracy wecan remove weight column

In [ ]:
from sklearn.feature_selection import RFECV

In [ ]:
lr=LogisticRegression(max_iter=1000)

In [ ]:
rfecv=RFECV(lr,cv=5)

In [ ]:
rfecv.fit(xtrain_scaled,ytrain_scaled)

RFECV(cv=5, estimator=LogisticRegression(max_iter=1000))

In [ ]:
rfecv.n_features_

np.int64(6)

In [ ]:
rfecv.support_

array([False, False,  True,  True,  True,  True,  True,  True, False])

In [ ]:
rfecv_features=x.columns[rfecv.support_]

In [ ]:
rfecv_features

Index(['Height_cm', 'Weight_kg', 'BMI', 'Activity_Level', 'Sugar_Level',
       'Cholesterol'],
      dtype='object')