<a href="https://colab.research.google.com/github/tarannump096-cpu/My-Projects/blob/main/Probability12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv("/content/train.csv")

In [ ]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
df1=df[["Survived","Pclass"]].dropna()

In [ ]:
df1

     Survived  Pclass
0           0       3
1           1       1
2           1       3
3           1       1
4           0       3
..        ...     ...
886         0       2
887         1       1
888         0       3
889         1       1
890         0       3

[891 rows x 2 columns]

In [ ]:
first_class_survived=len(df1[(df1["Survived"]==1 )& (df1["Pclass"]==1)])
second_class_survived=len(df1[(df1["Survived"]==1 )& (df1["Pclass"]==2)])
third_class_survived=len(df1[(df1["Survived"]==1 )& (df1["Pclass"]==3)])
first_class_not_survived=len(df1[(df1["Survived"]==0 )& (df1["Pclass"]==1)])
second_class__not_survived=len(df1[(df1["Survived"]==0 )& (df1["Pclass"]==2)])
third_class_not_survived=len(df1[(df1["Survived"]==0)& (df1["Pclass"]==3)])

In [ ]:
observed_matrix=np.array([[first_class_survived,second_class_survived,third_class_survived],
                          [first_class_not_survived,second_class__not_survived,third_class_not_survived]])

In [ ]:
observed_matrix

array([[136,  87, 119],
       [ 80,  97, 372]])

In [ ]:
from scipy.stats import chi2_contingency

In [ ]:
chi2,p,dof,expected=chi2_contingency(observed_matrix)

In [ ]:
p

np.float64(4.5492517112987287e-23)

In [ ]:
if p>5:
    print("there is no relation")
else:
    print("there is a relation")

there is a relation

In [ ]:
observed_matrix=pd.crosstab(df1["Survived"],df1["Pclass"])

In [ ]:
observed_matrix

Pclass      1   2    3
Survived
0          80  97  372
1         136  87  119